networks:
  api-internal:
    driver: bridge

services:
  mock-external-api:
    image: wiremock/wiremock:latest
    ports:
      - "3001:8080"
    volumes:
      - ./src/main/resources/wiremock:/home/wiremock/mappings
  postgres:
    image: postgres:16-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshelf
    ports:
      - "5432:5432"
    networks:
      - api-internal
    volumes:
      - /var/lib/postgresql/data
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/bookshelf
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
      - mock-external-api
    networks:
      - api-internal